image: maven:3.3.3-jdk-8
stages:
  - build
  - test
  - deploy
build_job:
  stage: build
  only:
    - master
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
  tags:
    - docker
build_merge_job:
  stage: build
  except:
    - master
    - tags
  script:
    - git merge origin master --no-commit --no-ff
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true
  tags:
    - docker
test_sonar_preview_job:
  stage: test
  except:
    - master
    - tags
  script:
    - git merge origin master --no-commit --no-ff
    - git log --pretty=format:%H origin/master..$CI_BUILD_REF | tr '\n' ','
    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$(git log --pretty=format:%H origin/master..$CI_BUILD_REF | tr '\n' ',') -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.unique_issue_per_inline=true
  tags:
    - docker
test_sonar_job:
  stage: test
  only:
    - master
  script:
    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN
    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar -Dsonar.host.url=$SONAR_OFF_URL -Dsonar.login=$SONAR_OFF_LOGIN
  tags:
    - docker